### PR TITLE
Add separate result attribute for problem regions.

### PR DESCRIPTION
**Pull request by jlselden**
Added `problem_regions` attribute to `pywim.smartslice.result.Result`.

This seems like it would be better than grouping it with `surface_mesh_results`.

### CODE REVIEW

**Review by bradymadams — COMMENTED** [review]
Seems a little off to me to define a `problem_regions` database just for using the underlying `problem_regions` attribute in the Database.

I think I'd be fine if it was part of the `surface_mesh_results`, or since the problem_regions are actually part of the FEA result maybe we call this `fea_results`, but we only store the problem regions in it for now. We could add other FEA results to it in the future, if necessary.

Thoughts?

**Comment by jlselden** [comment]
Yeah, I think calling it something more general like `fea_results` makes a lot of sense.

**Comment by jlselden** [comment]
Would it make sense to also move the `feasibility_results` to the `ModelResults` and also store those in the `fea_results` attribute?

**Comment by bradymadams** [comment]
I think we should avoid that. That will break backwards compatibility. Anytime we do that we need to plan it for a major release. We're not setup well yet to handle API breaking changes.

**Review by bradymadams — APPROVED** [review]

**Pull request merged**
