### PR TITLE
updated which errors we check for to reduce the headaches in Cura

### PR DESCRIPTION
**Pull request by dougkenik**
Let me know if the errors I removed are OK.

### CODE REVIEW

**Comment by dougkenik** [comment]
I'll update the tests once we agree on which errors to remove

**Comment by jlselden** [comment]
Am I correct in thinking that we're removing these checks as a convenience to the user? Internally, we still make these assumptions, so I guess we need to make sure that those settings are being enforced in some way.

**Comment by bradymadams** [comment]
> Am I correct in thinking that we're removing these checks as a convenience to the user? Internally, we still make these assumptions, so I guess we need to make sure that those settings are being enforced in some way.

These checks will need to be removed in all places so the job will run. It wouldn't make much sense to remove them on the front end just to throw the error on the back end. The smartslice module is making these checks using pywim, right? So these changes will propagate to smartslice?

**Comment by dougkenik** [comment]
> This is fine with me as long as we all understand the consequences of ignoring some of these. I think the initial layer adjustments are insignificant. However, changing the `skin_line_width`, `infill_line_width`, etc. could have a significant impact on the structural behavior.
> 
> Instead of commenting them out, how about we move them to a separate dictionary, `STRICT_REQUIREMENTS`, so they're available in case we want to re-use them in the plug-in at some point and we don't have to modify pywim again.

Moving them to a separate dictionary is a good idea. My reasoning for not including the skin and infill line widths is that the options of "extra fine", "fine", "normal" etc have these as different values.

**Comment by bradymadams** [comment]
Will merge pending @jlselden approval

**Pull request merged**
