### PR TITLE
R21.1 cutting mesh metadata fix

### PR DESCRIPTION
**Pull request by AijunHall**
Linked [PR](https://github.com/tetonsim/is-cura-ui/pull/597)

Copied the same check we have for infill meshes in the threemf model metadata over for cutting meshes.

### CODE REVIEW

**Comment by bradymadams** [comment]
@AijunHall is this a client side or server side fix? If server side, I assume we need to test this first.

**Comment by AijunHall** [comment]
> is this a client side or server side fix? If server side, I assume we need to test this first.

@bradymadams This would be a server side fix.

**Comment by bradymadams** [comment]
While I think this is a valid contribution to pywim, I think we should probably invalidate the job in `pywim.smartslice.job.Job.validate` if a cutting mesh is present. We have not done much testing with cutting meshes with SmartSlice and I don't think we want to support them until we have a chance to test them thoroughly.

**Comment by AijunHall** [comment]
Detecting the cutting mesh is trickier than I thought. Some changes need to be made in is-cura-ui to the way we detect modifier mesh nodes first I think.

Looking more into this

**Comment by AijunHall** [comment]
@bradymadams Now the presence of cutting meshes should invalidate the job.

**Review by bradymadams — APPROVED** [review]

**Pull request merged**
